client_id: '3MVG9YDQS5WtC11rEEbuE0ugmmxoFqE2nwkWgPIMnmmss56M7Lc90J0wULBI3_zBVbQy7Fh9ralCsTnz7DGt6'
client_secret: '201586777941315632'
username: 'sandeep@freshdesk.com'
password: 'networking@1ertQLxHO6goKkaBlsobChX0Pu'
debugging: true